version: '3.9'

# THIS IS A NO OP
# NO POINT OF USING DOCKER
# BECAUSE SQLITE WILL BE CREATEDD IN A FLAT FILE

services:

  # ADDING SQLITE SERVICE
  fancy-samoyed-serv:
    image: nouchka/sqlite3:latest
    container_name: fancy-samoyed
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
