version: '3.9'

services:

  # ADDING SQLITE
  fancy-samoyed-serv:
    image: nouchka/sqlite3:latest
    container_name: fancy-samoyed
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
